FILE_EXTENSIONS = {

    'video/mp4': '.mp4', 'video/3gpp': '.3gp', 'video/3gpp2': '.3g2',
    'video/x-msvideo': '.avi', 'video/x-ms-wmv': '.wmv', 'video/x-flv': '.flv',
    'video/quicktime': '.mov', 'video/x-matroska': '.mkv', 'video/webm': '.webm',
    'video/mpeg': '.mpeg', 'video/mp2t': '.ts', 'video/x-ms-asf': '.asf',
    'video/x-m4v': '.m4v', 'video/x-ms-vob': '.vob', 'video/x-ms-wmv': '.wmv',
    'video/x-dv': '.dv', 'video/x-f4v': '.f4v', 'video/x-mng': '.mng',
    'video/ogg': '.ogv', 'video/x-ogm': '.ogm', 'video/x-mpegurl': '.m3u8',
    'video/x-ms-afs': '.afs', 'video/x-ms-afs': '.afs', 'video/x-sgi-movie': '.movie',
    'video/x-theora': '.ogv', 'video/vnd.rn-realvideo': '.rv', 'video/x-anim': '.anim',
    'video/x-ms-wvx': '.wvx', 'video/x-ms-wm': '.wm', 'video/x-ms-wmx': '.wmx',
    'video/x-ms-wvx': '.wvx', 'video/x-ms-wmd': '.wmd', 'video/x-ms-wmv': '.wmv',

    'audio/mpeg': '.mp3', 'audio/wav': '.wav', 'audio/ogg': '.ogg',
    'audio/flac': '.flac', 'audio/aac': '.aac', 'audio/webm': '.webm',
    'audio/x-wav': '.wav', 'audio/x-aiff': '.aiff', 'audio/x-midi': '.mid',
    'audio/x-midi': '.midi', 'audio/x-ms-wma': '.wma', 'audio/x-ms-wax': '.wax',
    'audio/x-ms-wmv': '.wmv', 'audio/x-pn-realaudio': '.ra', 'audio/x-realaudio': '.ra',
    'audio/x-ape': '.ape', 'audio/x-m4a': '.m4a', 'audio/x-m4b': '.m4b',
    'audio/x-m4p': '.m4p', 'audio/x-m4r': '.m4r', 'audio/x-aac': '.aac',
    'audio/x-alac': '.alac', 'audio/x-dsf': '.dsf', 'audio/x-dff': '.dff',
    'audio/x-opus': '.opus', 'audio/x-speex': '.spx', 'audio/x-vorbis': '.ogg',
    'audio/x-tta': '.tta', 'audio/x-wavpack': '.wv', 'audio/x-musepack': '.mpc',
    'audio/x-optimfrog': '.ofr', 'audio/x-shorten': '.shn', 'audio/x-tak': '.tak',

    'image/jpeg': '.jpg', 'image/jpg': '.jpg', 'image/png': '.png',
    'image/gif': '.gif', 'image/webp': '.webp', 'image/bmp': '.bmp',
    'image/svg+xml': '.svg', 'image/tiff': '.tiff', 'image/x-tiff': '.tiff',
    'image/x-icon': '.ico', 'image/x-xcf': '.xcf', 'image/x-psd': '.psd',
    'image/x-ai': '.ai', 'image/heic': '.heic', 'image/heif': '.heif',
    'image/avif': '.avif', 'image/jp2': '.jp2', 'image/jpx': '.jpx',
    'image/jpm': '.jpm', 'image/mj2': '.mj2', 'image/raw': '.raw',
    'image/x-canon-cr2': '.cr2', 'image/x-canon-crw': '.crw',
    'image/x-nikon-nef': '.nef', 'image/x-nikon-nrw': '.nrw',
    'image/x-sony-arw': '.arw', 'image/x-sony-srf': '.srf',
    'image/x-olympus-orf': '.orf', 'image/x-pentax-pef': '.pef',
    'image/x-fuji-raf': '.raf', 'image/x-panasonic-rw2': '.rw2',
    'image/x-samsung-srw': '.srw', 'image/x-adobe-dng': '.dng',
    'image/x-photoshop': '.psd', 'image/x-illustrator': '.ai',
    'image/x-epson-eps': '.eps', 'image/x-pagemaker': '.pmd',
    'image/x-freehand': '.fh', 'image/x-coreldraw': '.cdr',
    'image/x-quarkxpress': '.qxp', 'image/x-autocad': '.dwg',
    'image/x-autocad-dxf': '.dxf', 'image/x-3ds': '.3ds',
    'image/x-blend': '.blend', 'image/x-obj': '.obj',

    'application/pdf': '.pdf', 'application/msword': '.doc',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document': '.docx',
    'application/vnd.ms-excel': '.xls',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': '.xlsx',
    'application/vnd.ms-powerpoint': '.ppt',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation': '.pptx',
    'application/vnd.oasis.opendocument.text': '.odt',
    'application/vnd.oasis.opendocument.spreadsheet': '.ods',
    'application/vnd.oasis.opendocument.presentation': '.odp',
    'application/vnd.oasis.opendocument.graphics': '.odg',
    'application/vnd.oasis.opendocument.formula': '.odf',
    'application/vnd.oasis.opendocument.database': '.odb',
    'application/rtf': '.rtf', 'text/rtf': '.rtf',
    'application/x-abiword': '.abw', 'application/x-latex': '.latex',
    'application/x-tex': '.tex', 'application/x-texinfo': '.texi',
    'application/x-fictionbook': '.fb2', 'application/x-mobipocket-ebook': '.mobi',
    'application/epub+zip': '.epub', 'application/x-ibooks+zip': '.ibooks',
    'application/vnd.amazon.ebook': '.azw', 'application/x-cbr': '.cbr',
    'application/x-cbz': '.cbz', 'application/x-cb7': '.cb7',
    'application/x-cbt': '.cbt', 'application/vnd.comicbook+zip': '.cbz',

    'application/zip': '.zip', 'application/x-rar-compressed': '.rar',
    'application/x-rar': '.rar', 'application/gzip': '.gz',
    'application/x-7z-compressed': '.7z', 'application/x-tar': '.tar',
    'application/x-bzip2': '.bz2', 'application/x-xz': '.xz',
    'application/x-zstd': '.zst', 'application/x-lzip': '.lz',
    'application/x-lzma': '.lzma', 'application/x-lzop': '.lzo',
    'application/x-ace': '.ace', 'application/x-arc': '.arc',
    'application/x-arj': '.arj', 'application/x-cpio': '.cpio',
    'application/x-shar': '.shar', 'application/x-ustar': '.ustar',
    'application/x-warc': '.warc', 'application/x-zoo': '.zoo',
    'application/vnd.ms-cab-compressed': '.cab', 'application/x-mscab': '.cab',
    'application/x-apple-diskimage': '.dmg', 'application/x-iso9660-image': '.iso',
    'application/x-nrg': '.nrg', 'application/x-mdf': '.mdf',
    'application/x-daemon': '.daa', 'application/x-cdi': '.cdi',

    'application/x-executable': '.exe', 'application/x-msdownload': '.dll',
    'application/x-msi': '.msi', 'application/x-mach-binary': '.o',
    'application/x-sharedlib': '.so', 'application/x-dosexec': '.com',
    'application/x-elf': '.elf', 'application/x-mach-o': '.dylib',
    'application/x-msdos-program': '.exe', 'application/vnd.microsoft.portable-executable': '.exe',
    'application/x-apple-executable': '.app', 'application/x-deb': '.deb',
    'application/x-redhat-package-manager': '.rpm', 'application/x-tar': '.tar',
    'application/x-java-archive': '.jar', 'application/x-java-jnlp-file': '.jnlp',
    'application/x-android-apk': '.apk', 'application/vnd.apple.installer+xml': '.mpkg',
    'application/x-ms-installer': '.msi', 'application/x-ms-shortcut': '.lnk',
    'application/x-shellscript': '.sh', 'application/x-bat': '.bat',
    'application/x-cmd': '.cmd', 'application/x-ps1': '.ps1',
    'application/x-vbscript': '.vbs', 'application/x-javascript': '.js',

    'application/x-sqlite3': '.sqlite', 'application/x-sqlite3': '.db',
    'application/x-sqlite3': '.sqlite3', 'application/x-mysql': '.sql',
    'application/x-postgresql': '.sql', 'application/x-mongodb': '.bson',
    'application/x-redis': '.rdb', 'application/x-leveldb': '.ldb',
    'application/x-rocksdb': '.ldb', 'application/x-couchdb': '.couch',
    'application/x-cassandra': '.cassandra', 'application/x-hbase': '.hbase',
    'application/x-elastic': '.es', 'application/x-kafka': '.kafka',
    'application/x-rabbitmq': '.rmq', 'application/x-mariadb': '.sql',
    'application/x-oracle': '.sql', 'application/x-sqlserver': '.sql',
    'application/x-dbase': '.dbf', 'application/x-paradox': '.db',
    'application/x-access': '.mdb', 'application/x-access2007': '.accdb',
    'application/x-filemaker': '.fmp12', 'application/x-lotus': '.nsf',

    'text/plain': '.txt', 'application/json': '.json', 'text/x-python': '.py',
    'text/x-java': '.java', 'text/x-c': '.c', 'text/x-c++': '.cpp',
    'text/x-c-header': '.h', 'text/x-csharp': '.cs', 'text/x-javascript': '.js',
    'text/x-typescript': '.ts', 'text/x-jsx': '.jsx', 'text/x-tsx': '.tsx',
    'text/x-html': '.html', 'text/x-htm': '.htm', 'text/x-css': '.css',
    'text/x-scss': '.scss', 'text/x-sass': '.sass', 'text/x-less': '.less',
    'text/x-json': '.json', 'text/x-yaml': '.yaml', 'text/x-yml': '.yml',
    'text/x-markdown': '.md', 'text/x-mdx': '.mdx', 'text/x-rst': '.rst',
    'text/x-shellscript': '.sh', 'text/x-bash': '.bash', 'text/x-zsh': '.zsh',
    'text/x-fish': '.fish', 'text/x-php': '.php', 'text/x-perl': '.pl',
    'text/x-perl6': '.raku', 'text/x-ruby': '.rb', 'text/x-go': '.go',
    'text/x-rust': '.rs', 'text/x-swift': '.swift', 'text/x-kotlin': '.kt',
    'text/x-kts': '.kts', 'text/x-scala': '.scala', 'text/x-sql': '.sql',
    'text/x-csv': '.csv', 'text/x-tsv': '.tsv', 'text/x-xml': '.xml',
    'text/x-dtd': '.dtd', 'text/x-xsd': '.xsd', 'text/x-xsl': '.xsl',
    'text/x-properties': '.properties', 'text/x-makefile': '.mk',
    'text/x-cmake': '.cmake', 'text/x-dockerfile': '.dockerfile',
    'text/x-nginx': '.conf', 'text/x-apache': '.conf', 'text/x-apt': '.list',
    'text/x-gitignore': '.gitignore', 'text/x-gitattributes': '.gitattributes',
    'text/x-docker-compose': '.yml', 'text/x-terraform': '.tf',
    'text/x-hcl': '.hcl', 'text/x-nomad': '.nomad', 'text/x-vault': '.hcl',
    'text/x-vue': '.vue', 'text/x-svelte': '.svelte', 'text/x-angular': '.ng',
    'text/x-graphql': '.graphql', 'text/x-sqlite': '.db',
    'text/x-ini': '.ini', 'text/x-config': '.cfg', 'text/x-conf': '.conf',
    'text/x-log': '.log', 'text/x-stdout': '.out', 'text/x-assembly': '.asm',
    'text/x-assembly64': '.s', 'text/x-nasm': '.nasm', 'text/x-masm': '.masm',
    'text/x-lua': '.lua', 'text/x-lisp': '.lisp', 'text/x-clisp': '.cl',
    'text/x-scheme': '.scm', 'text/x-haskell': '.hs', 'text/x-ocaml': '.ml',
    'text/x-elixir': '.ex', 'text/x-elixir': '.exs', 'text/x-elm': '.elm',
    'text/x-clojure': '.clj', 'text/x-clojurescript': '.cljs',
    'text/x-dart': '.dart', 'text/x-pascal': '.pas', 'text/x-fortran': '.f90',
    'text/x-cobol': '.cob', 'text/x-ada': '.adb', 'text/x-verilog': '.v',
    'text/x-vhdl': '.vhdl', 'text/x-systemverilog': '.sv',

    'font/ttf': '.ttf', 'font/otf': '.otf', 'font/woff': '.woff',
    'font/woff2': '.woff2', 'font/eot': '.eot', 'font/sfnt': '.sfnt',
    'application/x-font-ttf': '.ttf', 'application/x-font-otf': '.otf',
    'application/x-font-woff': '.woff', 'application/vnd.ms-fontobject': '.eot',

    'application/x-x509-ca-cert': '.crt', 'application/x-pem-file': '.pem',
    'application/x-pkcs12': '.p12', 'application/x-pkcs7-certificates': '.p7b',
    'application/x-pkcs7-certreqresp': '.p7r', 'application/x-pkcs7-mime': '.p7m',
    'application/x-pkcs7-signature': '.p7s', 'application/x-pkcs8': '.p8',
    'application/x-ssh-key': '.ssh', 'application/x-ssh-cert': '.ssh-cert',
    'application/x-pgp-key': '.pgp', 'application/x-pgp-signature': '.sig',
    'application/x-gpg-key': '.gpg', 'application/x-keepass': '.kdbx',
    'application/x-bitwarden': '.json', 'application/x-1password': '.opvault',

    'application/x-raw-disk-image': '.img', 'application/x-diskcopy': '.dmg',
    'application/x-vmdk': '.vmdk', 'application/x-vhd': '.vhd',
    'application/x-vhdx': '.vhdx', 'application/x-qcow': '.qcow',
    'application/x-qcow2': '.qcow2', 'application/x-ova': '.ova',
    'application/x-ovf': '.ovf', 'application/x-virtualbox': '.vbox',

    'model/stl': '.stl', 'model/obj': '.obj', 'model/mtl': '.mtl',
    'model/3mf': '.3mf', 'model/gltf+json': '.gltf', 'model/gltf-binary': '.glb',
    'model/vnd.collada+xml': '.dae', 'model/vnd.usdz+zip': '.usdz',
    'model/vnd.usda': '.usda', 'model/vnd.usdc': '.usdc',
    'model/x-step': '.step', 'model/x-iges': '.iges', 'model/x-3ds': '.3ds',
    'model/x-fbx': '.fbx', 'model/x-blend': '.blend', 'application/x-blender': '.blend',

    'application/vnd.google-earth.kml+xml': '.kml', 'application/vnd.google-earth.kmz': '.kmz',
    'application/x-shapefile': '.shp', 'application/x-geojson': '.geojson',
    'application/gpx+xml': '.gpx', 'application/vnd.garmin.tcx': '.tcx',
    'application/vnd.garmin.fit': '.fit', 'application/x-nmea': '.nmea',

    'application/x-netcdf': '.nc', 'application/x-hdf': '.hdf',
    'application/x-hdf5': '.h5', 'application/x-matlab-data': '.mat',
    'application/x-sas-data': '.sas7bdat', 'application/x-spss-data': '.sav',
    'application/x-stata-data': '.dta', 'application/x-r-data': '.rda',
    'application/x-python-pickle': '.pkl', 'application/x-julia-data': '.jld',
    'application/x-array': '.npy', 'application/x-array-zip': '.npz',

    'application/x-autocad': '.dwg', 'application/x-autocad-dxf': '.dxf',
    'application/x-solidworks': '.sldprt', 'application/x-inventor': '.ipt',
    'application/x-fusion360': '.f3d', 'application/x-step': '.stp',
    'application/x-iges': '.igs', 'application/x-stl': '.stl',
    'application/x-collada': '.dae', 'application/x-sketcup': '.skp',
    'application/x-rhino': '.3dm', 'application/x-alias': '.wire',

    'application/epub+zip': '.epub', 'application/x-mobipocket-ebook': '.mobi',
    'application/x-fictionbook': '.fb2', 'application/x-ibooks+zip': '.ibooks',
    'application/vnd.amazon.ebook': '.azw', 'application/x-azw3': '.azw3',
    'application/x-kindle': '.kfx', 'application/x-lit': '.lit',
    'application/x-pdb': '.pdb', 'application/x-prc': '.prc',

    'text/x-log': '.log', 'text/x-syslog': '.syslog', 'text/x-eventlog': '.evt',
    'text/x-audit': '.audit', 'application/x-json-log': '.json.log',
    'application/x-json-lines': '.jsonl', 'application/x-ndjson': '.ndjson',

    'text/x-toml': '.toml', 'text/x-xml': '.xml', 'text/x-dtd': '.dtd',
    'text/x-yaml': '.yaml', 'text/x-json': '.json', 'text/x-hcl': '.hcl',
    'text/x-nix': '.nix', 'text/x-jsxy': '.jsxy', 'text/x-edn': '.edn',
    'application/x-msconfig': '.msc', 'application/x-powershell': '.ps1',
    'application/x-batch': '.bat', 'application/x-registry': '.reg',
}